services:
  s1:
    build:
      context: .
    image: lutipri/hello-world
    ports:
      - 8085:8000
    networks:
      - coolify

  s2:
    image: lutipri/hello-world
    ports:
      - 8086:8000
    networks:
      - coolify

  http-echo:
    image: hashicorp/http-echo
    ports:
      - 8087:8080
    command: '-listen=:8080 -text="Preview deployment test Nr 2"'
    networks:
      - coolify

# networks:
#   ww0g4cwko8kksk004g8k4c4g: # network managed by Coolify and is created when deploying for the first time
#     external: true

networks:
  coolify: # network managed by Coolify and is created when deploying for the first time
    external: true
