services:
  s1:
    build:
      context: .
    image: lutipri/hello-world
    ports:
      - 8085:8000
    labels:
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0=https://s1.apps.caption.be' # Specifies the domain that Caddy should serve.
      - 'caddy_0.handle_path=/*'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 8000}}'  # Instructs Caddy to reverse proxy requests to the service on port 8000.
      - 'caddy_ingress_network=ww0g4cwko8kksk004g8k4c4g' # Indicates the Docker network that Caddy should use to connect to this service.
    networks:
      - ww0g4cwko8kksk004g8k4c4g

  s2:
    image: lutipri/hello-world
    ports:
      - 8086:8000
    labels:
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0=https://s2.apps.caption.be'
      - 'caddy_0.handle_path=/*'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 8000}}'
      - 'caddy_ingress_network=ww0g4cwko8kksk004g8k4c4g'
    networks:
      - ww0g4cwko8kksk004g8k4c4g

networks:
  ww0g4cwko8kksk004g8k4c4g: # network managed by Coolify and is created when deploying for the first time
    external: true
