services:
  s1:
    build:
      context: .
    image: lutipri/hello-world
    environment:
      - SERVICE_FQDN_S1_8000
    # ports:
    #   - 8085:8000
    labels:
      - 'traefik.http.middlewares.mybasicauth.basicauth.users=test:$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG'

  s2:
    image: lutipri/hello-world
    environment:
      - SERVICE_FQDN_S2_8000
    labels:
      # Router for /oauth2/*
      - "traefik.http.routers.http-0-u0c0s4owssskowsgscwwog8w-s2.rule=PathPrefix(`/oauth2/`)"
      - "traefik.http.routers.http-0-u0c0s4owssskowsgscwwog8w-s2.service=oauth2proxy-service"
      - "traefik.http.routers.http-0-u0c0s4owssskowsgscwwog8w-s2.middlewares=oauth2proxy"
      # Service definition
      - "traefik.http.services.oauth2proxy-service.loadbalancer.server.port=4180"
      - "traefik.http.services.oauth2proxy-service.loadbalancer.server.scheme=http"
      - "traefik.http.services.oauth2proxy-service.loadbalancer.server.url=http://oauth2-proxy-urartian:4180"
      # Middleware to set headers
      - "traefik.http.middlewares.oauth2proxy.headers.customrequestheaders.X-Real-IP={remote_host}"
      - "traefik.http.middlewares.oauth2proxy.headers.customrequestheaders.X-Forwarded-Uri={uri}"
      # ForwardAuth middleware
      - "traefik.http.middlewares.oauth2proxy.forwardauth.address=http://oauth2-proxy-urartian:4180/oauth2/auth"
      - "traefik.http.middlewares.oauth2proxy.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.oauth2proxy.forwardauth.authResponseHeaders=X-Real-IP,X-Auth-Request-Redirect"

      # Error Page Middleware
      - "traefik.http.middlewares.auth-error.redirectregex.regex=^.*$"
      - "traefik.http.middlewares.auth-error.redirectregex.replacement=https://s2.apps.caption.be/oauth2/sign_in?rd=https://{host}{uri}"
      - "traefik.http.middlewares.auth-error.redirectregex.permanent=false"

    # ports:
    #   - 8086:8000

  http-echo:
    image: hashicorp/http-echo
    environment:
      - SERVICE_FQDN_HTTPECHO_8080
    # ports:
    #   - 8087:8080
    command: '-listen=:8080 -text="Preview deployment test Nr 2"'

# networks:
#   ww0g4cwko8kksk004g8k4c4g: # network managed by Coolify and is created when deploying for the first time
#     external: true

# networks:
#   coolify: # network managed by Coolify and is created when deploying for the first time
#     external: true
