services:
  s1:
    build:
      context: .
    image: lutipri/hello-world
    environment:
      - SERVICE_FQDN_S1_8000
    # ports:
    #   - 8085:8000
    labels:
      - 'traefik.http.middlewares.auth@file'

  s2:
    image: lutipri/hello-world
    environment:
      - SERVICE_FQDN_S2_8000
    labels:
      - 'traefik.http.middlewares.urartian-oauth-middleware@docker'
      - 'traefik.http.middlewares.oauth2-error-handler@docker'
      - 'traefik.http.middlewares.oauth2-service-redirect@docker'
      
    # ports:
    #   - 8086:8000

  http-echo:
    image: hashicorp/http-echo
    environment:
      - SERVICE_FQDN_HTTPECHO_8080
    # ports:
    #   - 8087:8080
    command: '-listen=:8080 -text="Preview deployment test Nr 2"'

# networks:
#   ww0g4cwko8kksk004g8k4c4g: # network managed by Coolify and is created when deploying for the first time
#     external: true

# networks:
#   coolify: # network managed by Coolify and is created when deploying for the first time
#     external: true
