services:
  s1:
    build:
      context: .
    image: lutipri/hello-world
    ports:
      - 8085:8000
    networks:
      - frontend
    labels:
      - caddy_ingress_network=frontend
  s2:
    image: lutipri/hello-world   
    ports:
      - 8086:8000
    networks:
      - frontend
    labels:
      - caddy_ingress_network=frontend
      
networks:
  frontend:
    driver: bridge
